from __future__ import annotations
import hashlib, json
from datetime import datetime, timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; CORE=ROOT/'01_V2_CORE'; R389=ROOT/'06_R389_NATIVE_ROUTING'
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 bundle=load(R389/'R389_PROMOTION_REGRESSION_BUNDLE.json'); status=(R389/'R389_PROMOTION_REGRESSION_BUNDLE.status').read_text().strip()
 if status!='0' or bundle.get('status')!='PASS': raise SystemExit('promotion refused: regression bundle not PASS')
 checks=bundle['checks'];
 if checks['foundry_inherited']['test_files_passed']!=214 or checks['foundry_inherited']['test_files_failed']!=0 or checks['foundry_inherited']['tests_counted']!=806 or not checks['foundry_inherited']['byte_identical']: raise SystemExit('promotion refused: Foundry inheritance invalid')
 if checks['v2_direct']['test_files']!=49 or checks['v2_direct']['passed']!=49 or checks['v2_direct']['failed']!=0 or checks['v2_direct']['tests_counted']!=411: raise SystemExit('promotion refused: direct V2 gate incomplete')
 if checks['core_split_fresh']['status']!='PASS' or checks['core_split_fresh']['run_count']!=13 or checks['core_split_fresh']['failed']: raise SystemExit('promotion refused: core split gate incomplete')
 audit=load(CORE/'PRODUCT_QUALITY_AUDIT_R389.json'); overlay=load(CORE/'R389_PRODUCT_OVERLAY_STATE.json'); prior=load(CORE/'CURRENT_PRODUCT_AUTHORITY.json')
 tel=load(CORE/'generated_search/EXPERIMENT_TELEMETRY_INDEX_R12.json'); imap=load(CORE/'generated_search/INTERACTION_MAP_R12.json'); queue=load(CORE/'generated_v2_foundry/CORE_V2_FOUNDRY_COMPOSITION_QUEUE.json'); counts=load(CORE/'generated_v2_foundry/CORE_V2_FOUNDRY_COUNTS.json')
 campaign=[json.loads(x) for x in (CORE/'search_data/CAMPAIGN_MEMORY.jsonl').read_text().splitlines() if x.strip()]
 suite_dirs=sorted(d for d in (CORE/'products').glob('V2P*') if d.is_dir() and (d/'COMPOSITION.json').exists() and list(d.glob('test_*.py'))); suite_ids=[d.name.split('_',1)[0] for d in suite_dirs]
 assert prior['authority_release']=='R388' and prior['canonical_executable_suite_count']==48 and prior['canonical_distinct_family_count']==35
 assert audit['resulting_executable_suite_count']==49 and audit['resulting_distinct_family_count']==36 and audit['candidate_added_suite_ids']==['V2P050'] and audit['candidate_distinct_product_ids']==['V2P050'] and audit['registry455_unchanged']
 assert len(suite_ids)==49 and 'V2P050' in suite_ids and 'V2P047' not in suite_ids
 assert tel['event_count']==tel['exact_current_suite_matches']==411 and tel['current_completed_suite_count']==tel['calibrated_current_suite_count']==49 and tel['unmatched_event_count']==0
 assert imap['relation_counts']['COMPLETED_COMPOSITION']==49 and imap['relation_counts']['REJECTED_CURRENT_INTERFACE']==5
 fixed=[r for r in queue if r.get('experiment_bootstrap_status')=='FIXED_PILOT_SCHEDULE_AVAILABLE']; assert len(fixed)==49 and all(r.get('experiment_calibration_status')=='CALIBRATED_EXACT_SHELL' for r in fixed)
 assert sum(r.get('outcome')=='EXECUTABLE_CONTRACT_PASS' for r in campaign)==49 and sum(r.get('outcome')=='REJECTED_CURRENT_INTERFACE' for r in campaign)==5 and sum(bool(r.get('learning_eligible')) for r in campaign)==0
 assert counts['candidate_universe_rows']==16594 and counts['active_candidate_rows']==16589
 family_ids=list(prior['canonical_distinct_family_ids']); assert 'V2P050' not in family_ids; family_ids.append('V2P050'); assert len(set(family_ids))==36
 evidence=['06_R389_NATIVE_ROUTING/R389_PROMOTION_REGRESSION_BUNDLE.json','06_R389_NATIVE_ROUTING/R389_PROMOTION_REGRESSION_BUNDLE.status','06_R389_NATIVE_ROUTING/R389_R388_FOUNDRY_BYTE_IDENTITY.json','06_R389_NATIVE_ROUTING/R389_R388_CANONICAL_PRODUCT_BYTE_IDENTITY.json','06_R389_NATIVE_ROUTING/R389_ALL_V2_DIRECT_DISCOVERY_REGRESSION.json','06_R389_NATIVE_ROUTING/R389_SPLIT_CORE_REGRESSION.json','06_R389_NATIVE_ROUTING/R389_CANDIDATE_CLOSURE.log','06_R389_NATIVE_ROUTING/R389_V2P050_RAPID_PILOT.json','06_R389_NATIVE_ROUTING/R389_V2P050_QUALITY_ADJUDICATION.json','01_V2_CORE/PRODUCT_QUALITY_AUDIT_R389.json','01_V2_CORE/R389_PRODUCT_OVERLAY_STATE.json','01_V2_CORE/generated_search/EXPERIMENT_TELEMETRY_INDEX_R12.json','01_V2_CORE/generated_search/INTERACTION_MAP_R12.json','01_V2_CORE/generated_v2_foundry/CORE_V2_FOUNDRY_COUNTS.json']
 authority={'schema_version':1,'authority_release':'R389','status':'PROMOTED_CANONICAL_PRODUCT_AUTHORITY','promoted_at_utc':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'promotion_basis':'V2P050 SCIG admitted from the R388 parent-parent visibility frontier after hardened failure-region controls, fresh 13-case exact-shell telemetry, fresh state-sensitive core regression, and byte-identity-backed inheritance of unchanged R388 regression surfaces.','historical_base_authority':prior.get('historical_base_authority'),'prior_canonical_authority':{'release':'R388','executable_suites':48,'distinct_families':35},'registry_family_count':455,'registry455_unchanged':True,'canonical_executable_suite_count':49,'canonical_distinct_family_count':36,'canonical_executable_suite_ids':suite_ids,'canonical_distinct_family_ids':family_ids,'new_r389_executable_suite_ids':['V2P050'],'new_r389_distinct_family_ids':['V2P050'],'quarantined_product_ids':['V2P047'],'visibility_inheritance':prior.get('visibility_repairs',{}),'evidence_boundary':{'mechanics_telemetry_is_empirical_learning':False,'learning_eligible_campaign_events':0,'statement':'Promotion certifies graph visibility, deterministic executable contracts, failure-region controls and internal product-family distinctness only; it is not novel-theory, scientific, deployment or real-world validation.'},'promotion_gates':{'promotion_regression_bundle':'PASS','foundry_test_files_passed':214,'foundry_tests_counted':806,'foundry_inheritance_byte_identical':True,'direct_v2_test_files':49,'direct_v2_tests_counted':411,'direct_v2_failed':0,'core_surfaces_fresh':13,'core_tests_counted':checks['core_split_fresh']['tests_counted'],'candidate_closure_tests':8,'physical_suite_count':49,'distinct_family_count':36,'telemetry_events':411,'telemetry_exact_matches':411,'telemetry_unmatched':0,'calibrated_suites':49,'interaction_map_completed_edges':49,'fixed_pilotable_queue_rows':49,'campaign_mechanics_passes':49,'rejected_current_interface_edges':5,'candidate_universe_rows':16594,'active_candidate_rows':16589},'evidence_sha256':{p:sha(ROOT/p) for p in evidence}}
 (CORE/'CURRENT_PRODUCT_AUTHORITY.json').write_text(json.dumps(authority,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 overlay['status']='PROMOTED_TO_R389_PRODUCT_AUTHORITY'; overlay['promoted_as_authority_release']='R389'; overlay['current_authority_file']='CURRENT_PRODUCT_AUTHORITY.json'; overlay['promotion_regression_receipt']='06_R389_NATIVE_ROUTING/R389_PROMOTION_REGRESSION_BUNDLE.json'; (CORE/'R389_PRODUCT_OVERLAY_STATE.json').write_text(json.dumps(overlay,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 comp_path=CORE/'products/V2P050_SCIG/COMPOSITION.json'; comp=load(comp_path); comp['status']='R389_PROMOTED_CANONICAL_PRODUCT'; comp['authority']='R389_CANONICAL_PRODUCT_AUTHORITY'; comp_path.write_text(json.dumps(comp,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 cp=ROOT/'04_INTEGRITY/CURRENT_PRODUCT_COUNTS.json'; cc=load(cp); cc['canonical_product_authority']={'release':'R389','registry_family_count':455,'executable_suites':49,'distinct_families':36,'authority_file':'01_V2_CORE/CURRENT_PRODUCT_AUTHORITY.json','quarantined_product_ids':['V2P047']}; cc['completed_v2_executable_suites_not_folded_into_base_registry']=49; cc['quality_distinct_v2_families_not_folded_into_base_registry']=36; cc['registry455_unchanged']=True; cc['candidate_directed_edges']=16594; cc['ranked_working_queue_rows']=1000; cc['rejected_current_interface_edges_preserved_separately']=5; cp.write_text(json.dumps(cc,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 receipt={'release':'R389','result':'PROMOTED','authority_file':'01_V2_CORE/CURRENT_PRODUCT_AUTHORITY.json','authority_sha256':sha(CORE/'CURRENT_PRODUCT_AUTHORITY.json'),'overlay_state_sha256_after_promotion':sha(CORE/'R389_PRODUCT_OVERLAY_STATE.json'),'checks':authority['promotion_gates'],'registry455_unchanged':True,'quarantined_product_ids':['V2P047'],'note':authority['evidence_boundary']['statement']}
 (R389/'R389_AUTHORITY_PROMOTION_RECEIPT.json').write_text(json.dumps(receipt,indent=2,sort_keys=True,ensure_ascii=False)+'\n'); print(json.dumps(receipt,indent=2,ensure_ascii=False))
if __name__=='__main__': main()
