from __future__ import annotations
import hashlib,json
from datetime import datetime,timezone
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]; CORE=ROOT/'01_V2_CORE'; R390=ROOT/'07_R390_NATIVE_ROUTING'
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def sha(p): return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def main():
 bundle=load(R390/'R390_PROMOTION_REGRESSION_BUNDLE.json'); status=(R390/'R390_PROMOTION_REGRESSION_BUNDLE.status').read_text().strip()
 if status!='0' or bundle.get('status')!='PASS': raise SystemExit('promotion refused: regression bundle not PASS')
 c=bundle['checks']
 if c['foundry_inherited']['test_files_passed']!=214 or c['foundry_inherited']['test_files_failed']!=0 or c['foundry_inherited']['tests_counted']!=806 or not c['foundry_inherited']['byte_identical']: raise SystemExit('promotion refused: Foundry inheritance invalid')
 if c['v2_direct']['test_files']!=50 or c['v2_direct']['passed']!=50 or c['v2_direct']['failed']!=0 or c['v2_direct']['tests_counted']!=423: raise SystemExit('promotion refused: direct V2 gate incomplete')
 if c['core_split_fresh']['status']!='PASS' or c['core_split_fresh']['run_count']!=14 or c['core_split_fresh']['failed']: raise SystemExit('promotion refused: core split gate incomplete')
 audit=load(CORE/'PRODUCT_QUALITY_AUDIT_R390.json'); overlay=load(CORE/'R390_PRODUCT_OVERLAY_STATE.json'); prior=load(CORE/'CURRENT_PRODUCT_AUTHORITY.json')
 tel=load(CORE/'generated_search/EXPERIMENT_TELEMETRY_INDEX_R12.json'); imap=load(CORE/'generated_search/INTERACTION_MAP_R12.json'); queue=load(CORE/'generated_v2_foundry/CORE_V2_FOUNDRY_COMPOSITION_QUEUE.json'); counts=load(CORE/'generated_v2_foundry/CORE_V2_FOUNDRY_COUNTS.json')
 campaign=[json.loads(x) for x in (CORE/'search_data/CAMPAIGN_MEMORY.jsonl').read_text().splitlines() if x.strip()]
 suite_dirs=sorted(d for d in (CORE/'products').glob('V2P*') if d.is_dir() and (d/'COMPOSITION.json').exists() and list(d.glob('test_*.py'))); suite_ids=[d.name.split('_',1)[0] for d in suite_dirs]
 assert prior['authority_release']=='R389' and prior['canonical_executable_suite_count']==49 and prior['canonical_distinct_family_count']==36
 assert audit['resulting_executable_suite_count']==50 and audit['resulting_distinct_family_count']==37 and audit['candidate_added_suite_ids']==['V2P051'] and audit['candidate_distinct_product_ids']==['V2P051'] and audit['registry455_unchanged']
 assert len(suite_ids)==50 and 'V2P051' in suite_ids and 'V2P047' not in suite_ids
 assert tel['event_count']==tel['exact_current_suite_matches']==423 and tel['current_completed_suite_count']==tel['calibrated_current_suite_count']==50 and tel['unmatched_event_count']==0
 assert imap['relation_counts']['COMPLETED_COMPOSITION']==50 and imap['relation_counts']['REJECTED_CURRENT_INTERFACE']==5
 fixed=[r for r in queue if r.get('experiment_bootstrap_status')=='FIXED_PILOT_SCHEDULE_AVAILABLE']; assert len(fixed)==50 and all(r.get('experiment_calibration_status')=='CALIBRATED_EXACT_SHELL' for r in fixed)
 assert sum(r.get('outcome')=='EXECUTABLE_CONTRACT_PASS' for r in campaign)==50 and sum(r.get('outcome')=='REJECTED_CURRENT_INTERFACE' for r in campaign)==5 and sum(bool(r.get('learning_eligible')) for r in campaign)==0
 assert counts['candidate_universe_rows']==16594
 family_ids=list(prior['canonical_distinct_family_ids']); assert 'V2P051' not in family_ids; family_ids.append('V2P051'); assert len(set(family_ids))==37
 evidence=['07_R390_NATIVE_ROUTING/R390_PROMOTION_REGRESSION_BUNDLE.json','07_R390_NATIVE_ROUTING/R390_PROMOTION_REGRESSION_BUNDLE.status','07_R390_NATIVE_ROUTING/R390_R389_FOUNDRY_BYTE_IDENTITY.json','07_R390_NATIVE_ROUTING/R390_R389_CANONICAL_PRODUCT_BYTE_IDENTITY.json','07_R390_NATIVE_ROUTING/R390_ALL_V2_DIRECT_DISCOVERY_REGRESSION.json','07_R390_NATIVE_ROUTING/R390_SPLIT_CORE_REGRESSION.json','07_R390_NATIVE_ROUTING/R390_CANDIDATE_CLOSURE.log','07_R390_NATIVE_ROUTING/R390_V2P051_RAPID_PILOT.json','07_R390_NATIVE_ROUTING/R390_V2P051_QUALITY_ADJUDICATION.json','01_V2_CORE/PRODUCT_QUALITY_AUDIT_R390.json','01_V2_CORE/R390_PRODUCT_OVERLAY_STATE.json','01_V2_CORE/generated_search/EXPERIMENT_TELEMETRY_INDEX_R12.json','01_V2_CORE/generated_search/INTERACTION_MAP_R12.json','01_V2_CORE/generated_v2_foundry/CORE_V2_FOUNDRY_COUNTS.json']
 authority={'schema_version':1,'authority_release':'R390','status':'PROMOTED_CANONICAL_PRODUCT_AUTHORITY','promoted_at_utc':datetime.now(timezone.utc).replace(microsecond=0).isoformat(),'promotion_basis':'V2P051 SACDLW admitted from the R390 full-universe frontier after direct non-additive action/regret coupling, removal and collapse controls, synthetic nuisance-strength sensitivity, fresh 12-case exact-shell telemetry, fresh state-sensitive core regression, and byte-identity-backed inheritance of unchanged R389 product/Foundry regression surfaces.','historical_base_authority':prior.get('historical_base_authority'),'prior_canonical_authority':{'release':'R389','executable_suites':49,'distinct_families':36},'registry_family_count':455,'registry455_unchanged':True,'canonical_executable_suite_count':50,'canonical_distinct_family_count':37,'canonical_executable_suite_ids':suite_ids,'canonical_distinct_family_ids':family_ids,'new_r390_executable_suite_ids':['V2P051'],'new_r390_distinct_family_ids':['V2P051'],'quarantined_product_ids':['V2P047'],'visibility_inheritance':prior.get('visibility_inheritance',{}),'evidence_boundary':{'mechanics_telemetry_is_empirical_learning':False,'learning_eligible_campaign_events':0,'statement':'Promotion certifies graph visibility, deterministic executable contracts, failure-region controls and internal product-family distinctness only; it is not novel-theory, scientific, deployment or real-world validation.'},'promotion_gates':{'promotion_regression_bundle':'PASS','foundry_test_files_passed':214,'foundry_tests_counted':806,'foundry_inheritance_byte_identical':True,'direct_v2_test_files':50,'direct_v2_tests_counted':423,'direct_v2_failed':0,'core_surfaces_fresh':14,'core_tests_counted':c['core_split_fresh']['tests_counted'],'candidate_closure_tests':9,'physical_suite_count':50,'distinct_family_count':37,'telemetry_events':423,'telemetry_exact_matches':423,'telemetry_unmatched':0,'calibrated_suites':50,'interaction_map_completed_edges':50,'fixed_pilotable_queue_rows':50,'campaign_mechanics_passes':50,'rejected_current_interface_edges':5,'candidate_universe_rows':16594,'active_candidate_rows':counts['active_candidate_rows']},'evidence_sha256':{p:sha(ROOT/p) for p in evidence}}
 (CORE/'CURRENT_PRODUCT_AUTHORITY.json').write_text(json.dumps(authority,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 overlay['status']='PROMOTED_TO_R390_PRODUCT_AUTHORITY'; overlay['promoted_as_authority_release']='R390'; overlay['promotion_regression_receipt']='07_R390_NATIVE_ROUTING/R390_PROMOTION_REGRESSION_BUNDLE.json'; (CORE/'R390_PRODUCT_OVERLAY_STATE.json').write_text(json.dumps(overlay,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 comp_path=CORE/'products/V2P051_SACDLW/COMPOSITION.json'; comp=load(comp_path); comp['status']='R390_PROMOTED_CANONICAL_PRODUCT'; comp['authority']='R390_CANONICAL_PRODUCT_AUTHORITY'; comp_path.write_text(json.dumps(comp,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 cp=ROOT/'04_INTEGRITY/CURRENT_PRODUCT_COUNTS.json'; cc=load(cp); cc['canonical_product_authority']={'release':'R390','registry_family_count':455,'executable_suites':50,'distinct_families':37,'authority_file':'01_V2_CORE/CURRENT_PRODUCT_AUTHORITY.json','quarantined_product_ids':['V2P047']}; cc['completed_v2_executable_suites_not_folded_into_base_registry']=50; cc['quality_distinct_v2_families_not_folded_into_base_registry']=37; cc['registry455_unchanged']=True; cc['candidate_directed_edges']=16594; cc['ranked_working_queue_rows']=1000; cc['rejected_current_interface_edges_preserved_separately']=5; cp.write_text(json.dumps(cc,indent=2,sort_keys=True,ensure_ascii=False)+'\n')
 receipt={'release':'R390','result':'PROMOTED','authority_file':'01_V2_CORE/CURRENT_PRODUCT_AUTHORITY.json','authority_sha256':sha(CORE/'CURRENT_PRODUCT_AUTHORITY.json'),'overlay_state_sha256_after_promotion':sha(CORE/'R390_PRODUCT_OVERLAY_STATE.json'),'checks':authority['promotion_gates'],'registry455_unchanged':True,'quarantined_product_ids':['V2P047'],'note':authority['evidence_boundary']['statement']}
 (R390/'R390_AUTHORITY_PROMOTION_RECEIPT.json').write_text(json.dumps(receipt,indent=2,sort_keys=True,ensure_ascii=False)+'\n'); print(json.dumps(receipt,indent=2,ensure_ascii=False))
if __name__=='__main__': main()
