"""Self-contained local report for revision triage."""
import json


def write_revision_triage_report(result, path):
    payload = json.dumps(result, ensure_ascii=False).replace("</", "<\\/")
    page = r'''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Revision Triage</title><style>*{box-sizing:border-box}body{margin:0;background:#f3f6f7;color:#17333e;font:15px system-ui}header{background:#14333c;color:#fff;padding:28px max(24px,calc((100% - 1180px)/2))}main{max-width:1180px;margin:auto;padding:24px}.panel,.group{background:#fff;border:1px solid #d4e0e3;border-radius:9px;padding:18px;margin-bottom:16px}.metrics{display:grid;grid-template-columns:repeat(auto-fit,minmax(160px,1fr));gap:10px}.metric{background:#eaf1f2;padding:13px;border-radius:7px}.metric b{display:block;font-size:23px}.controls{display:flex;gap:14px;flex-wrap:wrap;align-items:end}label{display:grid;gap:5px}select,input{font:inherit;padding:9px;border:1px solid #afc2c8;border-radius:5px}.tag{display:inline-block;background:#e4efed;border-radius:99px;padding:4px 9px;margin:0 5px 5px 0}.reach{font-weight:700;color:#146b5a}.warning{border-left:4px solid #a87324;padding-left:12px}.muted{color:#5b727b}.representative{width:100%;border-collapse:collapse;font-size:13px}.representative td,.representative th{padding:8px;border-bottom:1px solid #e2eaed;text-align:left;vertical-align:top}a{color:#087461}@media(max-width:650px){.controls{display:grid}.representative{display:block;overflow:auto}}</style>
<header><h1>Revision Triage</h1><p id="revision"></p></header><main>
<section class="panel"><div class="metrics" id="metrics"></div><p id="coverage"></p><p><a href="../exact/index.html">Inspect raw comparison</a> · <a href="../exact/content.json">Raw comparison JSON</a> · <a href="triage.json">Triage JSON</a></p></section>
<section class="panel controls"><label>Change type<select id="category"><option value="">All types</option></select></label><label>Minimum resolved reach<input id="reach" type="number" min="0" value="0"></label><label>Sort<select id="sort"><option value="reach">Structural reach</option><option value="location">Sheet / location</option><option value="type">Change type</option></select></label></section>
<section id="groups"></section><section class="panel"><h2>Interpretation limits</h2><ul id="scope"></ul></section>
</main><script>const data=PAYLOAD,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={value_change:'Value changes',formula_logic_change:'Formula logic changes',formula_to_literal:'Formula → hardcode',literal_to_formula:'Hardcode → formula',added_content:'Added content',removed_content:'Removed content',movement_candidate:'Movement / reorder candidate',unresolved:'Unresolved / uncomparable'};
const m=data.summary;$('#revision').textContent=data.input_files.map(x=>x.name).join(' → ');$('#metrics').innerHTML=[['Raw changes',m.raw_change_count],['Triage groups',m.triage_group_count],['Compression',m.compression_ratio?m.compression_ratio+'×':'n/a'],['Groups with resolved impact',m.groups_with_resolved_impact]].map(x=>`<div class="metric"><span>${esc(x[0])}</span><b>${esc(x[1])}</b></div>`).join('');
const coverage=data.dependency_coverage||{};$('#coverage').className=coverage.unresolved_formula_count?'warning':'muted';$('#coverage').textContent=coverage.lineage_available?`${coverage.resolved_formula_count||0} / ${coverage.formula_count||0} formulas are in the resolved static graph; ${coverage.unresolved_formula_count||0} remain unresolved. Resolved reach is not numeric effect or audit significance.`:`Formula reach unavailable: ${coverage.reason||'no supported static graph'}`;
$('#category').innerHTML+=[...new Set(data.groups.map(g=>g.category))].sort().map(c=>`<option value="${c}">${esc(labels[c]||c)}</option>`).join('');
function rows(g){return g.representative_observations.map(o=>`<tr><td>${esc(o.left)}<br>${esc(o.left_value)}</td><td>${esc(o.right)}<br>${esc(o.right_value)}</td><td>${esc(o.comparison)}</td></tr>`).join('')}
function render(){let groups=data.groups.filter(g=>(!$('#category').value||g.category===$('#category').value)&&g.resolved_downstream_target_count>=Number($('#reach').value||0));const sort=$('#sort').value;groups.sort((a,b)=>sort==='reach'?b.resolved_downstream_target_count-a.resolved_downstream_target_count||a.id.localeCompare(b.id):sort==='type'?a.category.localeCompare(b.category)||a.sheet.localeCompare(b.sheet):a.sheet.localeCompare(b.sheet)||(a.left_range||'').localeCompare(b.left_range||''));$('#groups').innerHTML=groups.map(g=>`<article class="group"><span class="tag">${esc(labels[g.category]||g.category)}</span>${g.formula_transition?`<span class="tag">${esc(g.formula_transition)}</span>`:''}<h2>${esc(g.left_sheet)}!${esc(g.left_range||'∅')} → ${esc(g.right_sheet)}!${esc(g.right_range||'∅')}</h2><p>${g.changed_cell_count} changed/normalized positions · <span class="reach">${g.resolved_downstream_target_count} resolved terminal formula targets</span></p>${g.structural_movement_detected?`<p>Movement evidence: ${esc(g.movement_evidence.matching_rows)} matched rows, ${esc(g.movement_evidence.matching_cells)} matched cells; ${esc(g.movement_evidence.raw_changed_positions_normalized)} raw changed positions normalized.</p>`:''}${g.unresolved_coverage?`<p class="warning">${esc(g.unresolved_reasons.join(' '))}</p>`:''}<details><summary>Representative observations and reach</summary><table class="representative"><thead><tr><th>Before</th><th>After</th><th>Observation</th></tr></thead><tbody>${rows(g)}</tbody></table><p class="muted">${esc(g.resolved_downstream_targets.slice(0,20).join(', ')||'No resolved downstream terminal formula target.')}</p></details></article>`).join('')||'<section class="panel">No groups match the filters.</section>'}
$('#category').onchange=render;$('#reach').oninput=render;$('#sort').onchange=render;$('#scope').innerHTML=data.scope.map(x=>`<li>${esc(x)}</li>`).join('');render();</script></html>'''
    path.write_text(page.replace("PAYLOAD", payload), encoding="utf-8")
